# Generated by Django 5.1.2 on 2024-12-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_old_cart_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_cart',
            new_name='old_carts',
        ),
    ]
